#### Stage 1: Build the application
FROM openjdk:8
EXPOSE 8080
ADD target/SpringSecurityDemoAppApplication.jar SpringSecurityDemoAppApplication.jar
ENTRYPOINT ["java", "-jar", "/SpringSecurityDemoAppApplication.jar"]