version: "3.8"
services:


  securityclient:
    build:
      context: React Client 
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
      
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=forum
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306


  secuirtyserver:
    depends_on:
      - mysql
    build: 
      context: SpringBoot Backend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080" 

    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url":"jdbc:mysql://mysql:3306/forum",
        "spring.datasource.username":"root",
        "spring.datasource.password":"root",
        "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto":"update"
        }'